### ISSUE TITLE
Great work!! Can you help me?

### ISSUE THREAD

**Issue by gitaaronc** [pmezydlo/SPI_slave_driver_implementation#2]
Hi,

Great work with your SPI slave driver. It seems to be working great as a stand alone SPI slave.
Unfortunately I can't complete a successful test when I am using only a single BBB in a master & slave configuration.
I am running 4.4.9-bone10.
I have pins:
  P9_19 to P9_30
  P9_20 TO P9_32
  P9_23 TO P9_31
  P9_24 TO P9_33
which matches your drawing.

Which dts files should I echo to slots? Do I need to blacklist spi_omap2_mcspi when running in this configuration?

Thanks.

**Comment by pmezydlo** [comment]
Hi, 
I hate to tell you this, but launch  master and slave mode on one BeagleBoard can be difficult. 
The reason is that omap2 mcspi driver is installed automatically during the system's launching for both mcspi controllers. You turn it off completely after adding master driver to blacklist.

You can try to unbind the omap driver in / sys / bus / spi but I'm not sure if we can re-add the  slave driver.

You have to remember to remove a few lines of code from dts file

```
fragment@0 {
    target = <&spi1>;
    __overlay__ {
         status = "disabled";
    };
};
```

and change fragment@1 to fragment@0,

First you install master and then slave dts and slave driver.
As I find some time I will test it.

Thanks
Patryk

**Comment by gitaaronc** [comment]
I think the pins were off by 2. ie: P9_19 should be P9_17.
Which dts file needs to be changed? The slave dts file?

Thanks.
